name: branch_checkout
on: [push]
jobs:
  external-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
        with:
          fetch-depth: 1
          repository: 'abystoma/external-workflow'
          ref: branch 

      - name: Greeting
        run: cat greeting.txt || echo "greeting.txt not found"

      - name: Greetings
        run: cat greetings.txt || echo "greetings.txt not found"
